version: "3.9"
services:
  db:
    container_name: t3_db
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_USER: t3
      POSTGRES_PASSWORD: t3pass
      POSTGRES_DB: t3
    ports: ["5432:5432"]
    volumes:
      - ./packages/db/schema.sql:/schema.sql
      - ./scripts/seed.sql:/seed.sql

  search:
    container_name: t3_search
    image: opensearchproject/opensearch:2.13.0
    environment:
      discovery.type: single-node
      OPENSEARCH_SECURITY_ENABLED: "false"
    ports: ["9200:9200","9600:9600"]

  api:
    container_name: t3_api
    build:
      context: ./apps/api
    env_file:
      - ./.env
    ports: ["8080:8080"]
    depends_on:
      - db
      - search
